[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["cloudinary", "formidable"]

[dev]
  framework = "none"
